server:
  port: 9090

spring:
  application:
    name: healthy
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/health_management?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  ai:
    openai:
      chat:
        base-url: https://api.deepseek.com
        options:
          model: deepseek-chat
      api-key: sk-ef663e51e8224d99803c7fbc6f137a86

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.healthy.mapper: debug
